### PR TITLE
New and improved SQL Always On template

### PR DESCRIPTION
**Pull request by JeffGoldner**
Many improvements including realistic VM sizes, ability to select how many data disks, select the sample database name, supports SQL 2016 SP1 and SP2 on Windows Server 2016 (2017 in development), shortened names to be compliant with NetBIOS lengths.

Replaces sql-2016-ha.

### CODE REVIEW

**Comment by bganapa** [comment]
@knithinc , @vikasnav to review

**Comment by cblackuk** [comment]
True godsend, cannot wait for this to be merged so we can start using it properly.

**Comment by JackLeo** [comment]
Do this also include #367 ?

**Comment by cblackuk** [comment]
@JackLeo it does ->  

           "sqlServerOffer": {
                "type": "string",
                "allowedValues": [
                    "SQL2016SP1-WS2016",
                    "SQL2016SP2-WS2016"
            ],
                "metadata": {
                    "description": "The SQL Server Version"
                },
                "defaultValue": "SQL2016SP2-WS2016"
            },

It is just done slightly different this time around but it supports SP2 and is in fact the default.

**Pull request merged**
